import { createServerClient } from '@/lib/supabase/server';

export type AuditAction = 
  | 'create_user'
  | 'update_user'
  | 'delete_user'
  | 'deactivate_user'
  | 'create_document'
  | 'update_document'
  | 'approve_document'
  | 'reject_document'
  | 'create_training'
  | 'update_training'
  | 'assign_training'
  | 'create_handbook'
  | 'update_handbook'
  | 'login'
  | 'logout'
  | 'change_password'
  | 'update_profile';

export async function logAuditTrail(
  userId: string,
  action: AuditAction,
  entityType: 'user' | 'document' | 'training' | 'handbook' | 'system',
  entityId?: string,
  details?: Record<string, any>
) {
  try {
    const supabase = createServerClient();

    // Column names match the schema: resource_type, resource_id, changes, created_at
    const { error } = await supabase.from('audit_logs').insert({
      user_id: userId,
      action,
      resource_type: entityType,
      resource_id: entityId || null,
      changes: details || null,
      ip_address: 'unknown',
      // created_at is auto-generated by the database
    });

    if (error) {
      console.error('Audit log error:', error);
    }
  } catch (error) {
    console.error('Failed to log audit trail:', error);
  }
}

export async function getAuditLogs(
  userId?: string,
  action?: AuditAction,
  limit: number = 100
) {
  try {
    const supabase = createServerClient();

    let query = supabase
      .from('audit_logs')
      .select('*')
      .order('timestamp', { ascending: false })
      .limit(limit);

    if (userId) {
      query = query.eq('user_id', userId);
    }

    if (action) {
      query = query.eq('action', action);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Fetch audit logs error:', error);
      return { success: false, error: error.message };
    }

    return { success: true, data };
  } catch (error) {
    console.error('Failed to fetch audit logs:', error);
    return { 
      success: false, 
      error: error instanceof Error ? error.message : 'Failed to fetch audit logs' 
    };
  }
}
